[package]
name = "ferrishot"
version = "0.2.0"
license = "MIT OR Apache-2.0"
edition = "2024"
description = "A cross-platform desktop screenshot app"
repository = "https://github.com/nik-rev/ferrishot"
homepage = "https://github.com/nik-rev/ferrishot"
keywords = ["screenshot", "screen-capture", "capture", "flameshot"]
categories = ["visualization", "multimedia"]
authors = ["Nik Revenco"]

[build-dependencies]
image = "0.25.6"

[dependencies]
mouse_position = "0.1.4"
xcap = { version = "0.4.1", features = ["image", "vendored"] }
iced = { package = "ferrishot_iced", version = "0.14.1", features = [
  "canvas",
  "image",
  "web-colors",
  "advanced",
  "svg",
  "wgpu",
  "tokio",
  "qr_code",
] }
image = "0.25.6"
thiserror = "2.0.12"
delegate = "0.13"
env_logger = "0.11.8"
log = "0.4.27"
easy-ext = "1.0.2"
derive_more = { version = "2.0.1", features = ["is_variant"] }
arboard = { version = "3.5", features = ["wayland-data-control"] }
notify-rust = { version = "4.11.7", features = ["images"] }
clap = { version = "4.5.35", features = ["derive"] }
rfd = "0.15.3"

etcetera = "0.10.0"
chrono = "0.4.40"
tempfile = "3.19.1"
reqwest = { version = "0.12.15", default-features = false, features = [
  "rustls-tls",
  "json",
  "multipart",
  "stream",
] }
base64 = "0.22.1"
serde = "1.0.219"
serde_json = "1.0.140"

documented = "0.9.1"

# configuration
knus = { version = "3.2.0", git = "https://github.com/jaxter184/knus", rev = "01348798018b2e8443eaf40ef357775a6aba0ac6" }
miette = { version = "7.5.0", features = ["fancy"] }
strum = { version = "0.27.1", features = ["derive"] }
human_bytes = "0.4.3"
humantime = "2.2.0"
tokio = { version = "1.44.2", features = ["full"] }

[lints.rust]
missing_docs = "warn"

[lints.clippy]
pedantic = { priority = -1, level = "warn" }
nursery = { priority = -1, level = "warn" }

too_many_lines = "allow"
# casts from floats -> int are common in the code, and in
# most cases we don't care about precision as we are
# dealing with pixels which cannot be float.
cast_sign_loss = "allow"
cast_possible_truncation = "allow"
cast_precision_loss = "allow"

allow_attributes_without_reason = "warn"
unwrap_used = "warn"
missing_assert_message = "warn"
missing_docs_in_private_items = "warn"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
codegen-units = 1
lto = true
