[target.aarch64-apple-darwin]
linker = "rust-lld"
# NOTE: `rustdoc` doesn't currently respect the `linker` setting — keep an eye
# on this issue: https://github.com/rust-lang/rust/issues/125657
rustdocflags = ["-Clink-arg=-fuse-ld=lld"]

# NOTE: Also annoyingly, `target.<cfg>` doesn't let you set `rustdocflags`, so
# something like `[target.'cfg(target_os = "macos")']` doesn't work here and
# this repetition is needed...
[target.x86_64-apple-darwin]
linker = "rust-lld"
rustdocflags = ["-Clink-arg=-fuse-ld=lld"]
